name: Build

on: 
  push:
    branches:
      - 'master'
      - '**-GX'
    pull_request
    release:
    	types: [published]

jobs:
  build:
    env:
      BuildProps: src\GXOdata.Client.All\Directory.Build.props
      Configuration: Release
      NuspecFile: GXOData.Client.nuspec
      PackageFolder: build/packages/
      SolutionFile: GXOData.Client.sln

    runs-on: windows-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v2
        with:
          fetch-depth: 0

    - name: Restore
      run: dotnet restore $Env:SolutionFile

    - name: Prepare Nuspec and Build
      run: |
        [xml]$build_props = Get-Content $Env:BuildProps
        $PACKAGE_VERSION = $build_props.Project.PropertyGroup.AssemblyVersion
        if (!$PACKAGE_VERSION) {
          Write-Output "Unable to find package version in Nuspec file"
          exit 1
        }

        $COMMITS_INTERVAL = (git describe --tags --abbrev=0) + '..HEAD'
        $BUILD_NUMBER = git rev-list --first-parent --count $COMMITS_INTERVAL

        $NEW_PACKAGE_VERSION = $PACKAGE_VERSION
        if ("${{ github.ref }}".StartsWith("refs/heads/")) {
          $NEW_PACKAGE_VERSION = $NEW_PACKAGE_VERSION + '-rc' + $BUILD_NUMBER
        }

        [xml]$xml = Get-Content $Env:NuspecFile
        $xml.package.metadata.version = $NEW_PACKAGE_VERSION
        $xml.package.metadata.repository.branch = $Env:GITHUB_REF
        $xml.package.metadata.repository.commit = $Env:GITHUB_SHA

        $xml.Save($Env:NuspecFile)

        dotnet msbuild $Env:SolutionFile -p:Configuration=$Env:Configuration /t:Clean,Build

    - name: Package
      run: dotnet pack $Env:SolutionFile --output $Env:PackageFolder /p:NuspecFile=..\..\$Env:NuspecFile

    - name: Publish
      if: github.repository_owner == 'GeneXusLabs' && github.base_ref == ''
      env:
        GPRUrl: https://nuget.pkg.github.com/genexuslabs/index.json
      run: dotnet nuget push build\packages\GXOData.Client.*.nupkg --source $Env:GPRUrl --api-key ${{ secrets.SECURE_TOKEN }}

