name: Package GXOdata.Client.All

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Setup NuGet Repo
      run: nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/genexuslabs/index.json" -UserName %GITHUB_ACTOR% -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Restore
      run: dotnet restore GXOData.Client.sln
    - name: Build
      run: msbuild GXOData.Client.sln /p:Configuration=Release
    - name: Prepare Nuspec
      run: |
        $FILENAME = "GXOData.Client.nuspec"
        (gc $FILENAME) -replace '#GIT_BRANCH#', $Env:GITHUB_REF | Out-File -encoding ASCII $FILENAME
        (gc $FILENAME) -replace '#GIT_SHA#', $Env:GITHUB_SHA | Out-File -encoding ASCII $FILENAME
    - name: Package
      run: nuget pack GXOData.Client.nuspec -OutputDirectory build/packages/ -OutputFileNamesWithoutVersion
    - name: Publish
      run: nuget push build\packages\GXOData.Client.nupkg -Source "GPR"


